### ISSUE TITLE
Centered MvM money customization

### ISSUE THREAD

**Issue by marysiamzawka** [n0kk/ahud#105]
Hey, would you consider adding an option to have the remaining money counter centered (below the screen center/xhair) in MvM?
Cheers

**Comment by n0kk** [comment]
I probably won't add it as a customization since it would be a very niche feature, but it's actually really easy to change this yourself!

Find `hudmannvsmachinestatus.res` in `resource\ui` and simply edit the xpos and ypos of *InWorldCurrencyPanel*. Something like xpos c-50 and ypos c20 might work (no need to restart the game either to test changes; `hud_reloadscheme` in console works with these kind of edits).
