### ISSUE TITLE
Weird looking main menu

### ISSUE THREAD

**Issue by Cavna** [n0kk/ahud#107]
it looks really weird for me to have that dark and light bars when u click find a game...
![image](https://user-images.githubusercontent.com/40172308/41234423-b45ac20e-6dbe-11e8-9dc2-4d175cd6c625.png)

**Comment by Cavna** [comment]
and the damage numbers are also broken

**Comment by n0kk** [comment]
Since the Jungle Inferno update, the darkened overlay for the mode selection panel has not been modifiable. Unfortunately that's how the panel looks.

What do you mean damage numbers are broken? If you mean you cannot change the colors, they are now edited through the Advanced Options menu, or through console commands `hud_combattext_red`, `hud_combattext_green`, and `hud_combattext_blue`.

**Comment by Cavna** [comment]
well the numbers are not modify by the mod? before the update the numbers color and the front are modified by the hud?

**Comment by n0kk** [comment]
The font and size can still be modified through the HUD files, but the damage colors are now edited through the game since a few updates ago.
