### ISSUE TITLE
Ahud-cc secondary branch

### ISSUE THREAD

**Issue by jakadak001** [n0kk/ahud#128]
Hello,
Let me introduce myself. 
My name is David/Jakadak and I am a great fan of work your work.

I am currently working on customized Ahud with support of creators.tf server's commands and some advanced personalization hud improvements like robot+player destrution game mode, animated crosshair, enable fond support for more language, full screen side menu, in-game menu fix buttons, 4 types of close captions and more.

I would really like to collaborate with you. Would you be so kind and make a secoundary branch, that I will have access to?
My current repository: https://github.com/jakadak001/ahud-cc

Sincerely yours,
Jakadak/David Kolář

**Comment by n0kk** [comment]
You can go ahead and create a fork; no need for my permission. Anyone's free to edit this HUD for their own personal preferences. I won't be collaborating as I don't play the game anymore and I feel like I've done what I wanted with ahud. I only make slight fixes and adjustments when I have the time and desire now.

Good luck with the project.

**Comment by CriticalFlaw** [comment]
@n0kk The user who originally opened this issue is trying to get his account removed completely. They've emailed me asking for this issue to be deleted (not just closed) so that they can proceed with the deletion. I don't have the permissions to do it so could you please delete this issue on behalf of the OP?
