### ISSUE TITLE
ahud glitch

### ISSUE THREAD

**Issue by MrScales** [n0kk/ahud#20]
The loot screen glitches to the left in MVM
http://i.imgur.com/fxrSLXm.png

**Comment by alvinthechipmunk** [comment]
Same Issue from #15 Issue 2.

**Comment by n0kk** [comment]
Yeah, I've been working with MvM here and there the past few days, but this part still eludes me. I'm unable to find what res file or variable controls those tabs. Recording a demo to go back to it doesn't work because the loot screen doesn't appear when replaying the demo. When the glitch was first mentioned, I hadn't even touched the MVM side of the HUD in a while.

The search continues...

**Comment by n0kk** [comment]
Another small update: I have seen the same glitch occur in other HUDs, not just mine, and asking around, I found out it occasionally happens in the default HUD too. Not sure what causes it still unfortunately.
