### ISSUE TITLE
Killstreak

### ISSUE THREAD

**Issue by MrScales** [n0kk/ahud#22]
The killstreak icon is the heavy emblem. http://i.imgur.com/LEvjHFm.jpg

**Comment by n0kk** [comment]
The icon is actually the ammo icon, not a killstreak icon. When playing medic, it shows how how much ammo the player you are healing currently has in their clip. By default, it uses the heavy icon on all classes, but technically you can edit the `AmmoIcon` section in `targetid.res` in order to use, for example, the Pyro icon.

**Comment by MrScales** [comment]
I'm pretty sure that's a ks icon because every time my friend killed someone it went up one and it corresponded with the kill feed.But, then again I might be mistaken.

**Comment by n0kk** [comment]
It is indeed the ammo icon and count.
