### ISSUE TITLE
Damage on scoreboard incorrect

### ISSUE THREAD

**Issue by justinsamsel** [n0kk/ahud#27]
The damage reported on the 6v6 scoreboard never matches (sometimes by several thousand) the damage on the final log on sites like logs.tf. Is the damage being calculated incorrectly in the hud or the website?

**Comment by n0kk** [comment]
TF2 calculates real damage. If you backstab a Scout, the damage done is 750 (correct me if I'm wrong), even though the scout is only at 125 health. Only 125 damage is calculated to the scoreboard. I BELIEVE logs.tf calculates total damage (750), which is why you'll sometimes see spies top damaging in Highlander logs. SizzlingStats does real damage I think.

**Comment by justinsamsel** [comment]
Wow thanks for the fast reply. I appreciate the time you take to update this HUD and to respond to this question.

Is it possible to toggle the damage calculation method back and forth? It doesn't seem like ahud used to calculate damage this way. I upgraded to the newest version this week and noticed the change right away.

It's not that I want to see those big numbers to stroke my e-peen, it's just that it's very confusing to compare the numbers to logs.tf and makes it hard for me to grasp how effective I actually was in a game compared to my teammates and also compared to the enemy.

**Comment by ThePsionic** [comment]
The numbers come from TF2. ahud just gives them another appearance.

**Comment by n0kk** [comment]
Yeah, I didn't change anything in terms of how it's calculated. Straight from the game. I just change the appearance/position/etc. on the scoreboard.

**Comment by justinsamsel** [comment]
Thanks for the responses guys.
