### ISSUE TITLE
AHUD Issues+Requests

### ISSUE THREAD

**Issue by Seranok** [n0kk/ahud#38]
Hey mate, this HUD felt very appealing to me and in fact I liked it so much. However I seen some issues that might be addressed to you. Im not a scripter or anything but I love this HUD and can see it taken to greater heights.
Issues:-
1. Whenever I enter a game, and Then I play ESC or (,) to change class, the class or option menu and everything appears. But then the health bar and charge meters glitch in the background. Would request to fix that. I went into a community server TF2x10. Dont know if its the servers.
2. In most of the servers, the kill feed isn't visible. Mainly because of its text aligns with the color of the map. So I would request you to make a sort of black transparent rectangular black box with curved ends on all the kill feeds. Would like to see that.
Requests:-
1. Hit marker. Pretty sure you know about that.
2. A better background in start page. For example mine shows only of the guns in the gun mettle update. I would prefer to make a custom AHUD TF2 background.
3. Whenever we try to change class we have to move all the way down to change loadout, when we do that our cursor moves to the last class. Otherwise we have to select class the move the mouse all around 180 degrees to reach change loadout. In such situation I request you, whenever someone chooses the class, the change loadout must immediately be aligned to the right of the chosen class. Would love to see that. 
Thanks.

**Comment by LaMqTa** [comment]
Are you sure you don't have damaged hud files? The hud is working perfectly for me without any of the problems on your post. Weird.

**Comment by Seranok** [comment]
Wow that was fast. And no sir I dont have damaged HUD files. Any idea how to add hit markers?

**Comment by LaMqTa** [comment]
No idea it, sorry!

**Comment by n0kk** [comment]
Regarding the issues:

1. I can't duplicate this problem. Everything on the HUD remains static and in the background when I open up the menu or class menu. 

2. I haven't had an issue with the killfeed other than the text of a control point being highlighted upon capture or defending it, which doesn't contrast well against the whitish background. I won't be changing the appearance of the killfeed, but you can head over to `scripts` and open up `hudlayout.res`, search for `HudDeathNotice` and edit the various colors there, as well as rounding the corners (`CornerRadius`). 

Requests:

1. There is damage flash for crosshairs available as an option. Read the Customization section on the main GitHub repo page to find out how to enable it.

2. You see the Gun Mettle background right now all the time because its the current promo event TF2 is doing. It usually rotates between the stock TF2 background images and the monthly full moon/Halloween background. I won't be adding a custom background, but there are various guides on how to add your own readily available.

3. I usually enter the class loadout via the backpack or keyboard shortcut, so I completely missed this small annoyance. I can definitely reposition the Edit Loadout button to a better spot.

Thanks for the input

**Comment by Seranok** [comment]
The last request was not precisely interpreted. What I meant to say was whenever you move the cursor across any class, the change loadout must be shown right next to class loadout. For example
when you move your cursor against scout or soldier, it should be like this.
when scout is selected then, Scout ⇨Change loadout. 
Soldier  ⇨Change loadout and so on
Another thing is with the class animations. Can you make it bigger? Im running 1366x768.
Thanks.

**Comment by Seranok** [comment]
Also the class choosing or changing manual. Red or blue or spectator one. Make it bigger mate?

**Comment by n0kk** [comment]
1. Not possible as far as I know. There's only one static Edit Loadout Button. 
2. Class animations? 
3. You can disable in-game crosshairs in options. This shouldn't be a problem.

I don't know what you mean by the last post or "changing manual."

**Comment by Seranok** [comment]
Ok. Now basically I need some help. 
1. Any idea how to resent back the ingame ui to default tf2 ui.
2. Also the change loadoutnpage to default tf2. 
I dont want to revert anything else. Thanks.

**Comment by n0kk** [comment]
1. You'll have to delete or edit `hudplayerheath.res` and `hudanimations_tf.txt`.
2. Delete `classselection.res`.
3. Read a tutorial on installing different crosshairs such as [this one](http://huds.tf/forum/showthread.php?tid=22)

You're asking for various changes that stray from the original design of ahud, so I can't help you further. Your best bet is to learn how to edit HUDs on your own by reading a guide like Doodle's [TF2 HUD Editing Guide](http://doodlesstuff.com/?tutorial=tf2hud) or watch rays' video [TF2 HUD Tutorials](https://www.youtube.com/playlist?list=PL5eNrB8RrXXvohogCcKNKyk9SJxa26ltz).

Good luck.
