### ISSUE TITLE
Trade up menu not present on 3x monitor setup

### ISSUE THREAD

**Issue by ShdSteel** [n0kk/ahud#41]
Just wanting to inform about the issue that the trade up menu still doesnt display correctly. After updating ahud from before the gun mettle update to the current August 27th patch, I no longer get the envelope screen, but I am unable to view the post card looking background of what is supposed to be the trade up menu. 

![image](https://cloud.githubusercontent.com/assets/14268754/9842418/8345ba9a-5a73-11e5-8f8e-e2e11d4e8534.png)

Its not too big of a deal but just thought Id give my input on it, also ahud works great on 3x surround monitor setups so thank you!

One other thing Id like to as is if there is a way for me to have several things moved to near middle of my screen so that they show up on my middle monitor and not on the side ones.

**Comment by n0kk** [comment]
I just tested the Trade-up feature and the panel with the postcard appears (I can't test the envelope page since I don't have enough skins to trade up). Have you tried using the Trade-up feature while playing the game on a single monitor? It may or may not be a resolution issue, but I don't have 3 monitors to test it out. If all else fails, try doing a clean install of the HUD.

About moving HUD elements: yeah, definitely possible. You'll have to find the property in `hudlayout.res` of the element you want moved and experiment with the xpos value. Some elements, such as the health numbers, don't have a property in `hudlayout.res` so you'll have to find the .res file in `resource/ui/`

**Comment by ShdSteel** [comment]
Ok so that seemed to have worked, just switching my resolution from 5760x1080 to 1920x1080 made the post card appear, any ideas on why thats so?

**Comment by n0kk** [comment]
My guess is that some menus and panels don't work well with 3 monitors. Try it out with the default HUD and see if it is still an issue. 

https://github.com/n0kk/ahud/commit/832a2fbabcbea83883e48c89aff23f747e9b0504

This was all that was added to `hudanimations_tf.txt` for the Trade-up feature, straight from the stock file with no changes.
