### ISSUE TITLE
Pass Time Crash

### ISSUE THREAD

**Issue by Shr0b** [n0kk/ahud#43]
So I decided to try out TF2's new pass time gamemode for the first time to see what it was like, but I hardly actually got a chance to play it due to the fact that whenever someone else got the ball and could see me, the game instantly closed with no error and the server saying my authentication ticket had been cancelled. I turned off ahud without changing anything else and it fixed the problem, which leads me to believe it has something to do with the box that comes up when someone can pass the ball to you that says "in pass range" or whatever.

**Comment by n0kk** [comment]
Yeah, Valve keeps updating the files with updates they put out, so for the future, since the game mode is in beta, I'm gonna take out these files to avoid further problems.

The file to delete are: 

in `resource\ui`
* `hudpasstimeballstatus.res`
* `hudpasstimeoffscreenarrow.res`
* `hudpasstimepassnotify.res`
* `hudpasstimeteamscore.res`

in `resource\ui\notifications`
* `notifications/notify_passtime_howto.res`

**Comment by n0kk** [comment]
Fixed by commit https://github.com/n0kk/ahud/commit/63babf47bc5fdbed226c91141ceeee0da3fec020
