### ISSUE TITLE
Obfuscated Characters

### ISSUE THREAD

**Issue by AgentTroll** [n0kk/ahud#55]
**Problems (2)**
Basically anywhere there isn't an image or text, such as scroll arrows or checkboxes, **I have these a random characters or letters in their place**. The alert (triangle caution sign in the top left) **seems to be shifted to the right and slightly hiding behind the mail button**, even though you need to click in it's original spot in order to open it. 

I've attached an image of the Advanced Options menu to demonstrate. I unfortunately don't have a screenshot of the misplaced alert button, but I think you get the idea. If you need more screenies, I can take screenshots of those as well

**What I've tried**
- I've attempted to redownload and reextract to the `custom` directory in case it might have been corrupted, but that didn't fix it. 
- I've tried reloading the hud using `hud_reloadscheme`, which yielded no result as well. 
- I've googled this to try to find a solution, but I have no idea what to call it. I looked up "obfuscated characters" and "random characters" with "tf2 hud" but no promising results came up.
- Looking through the closed issues, but there's nothing as far as I can see about this particular issue.

**Other information**
- Output of `lsb_release -a`:

```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.2 (jessie)
Release:    8.2
Codename:   jessie
```
- Image/kernel version/whatever `uname` pulls out: `3.16.0-4-amd64`
- GeForce GTX 970/PCIe/SSE2, Intel® Core™ i3-3240 CPU @ 3.40GHz × 4
- Graphics driver version (Don't know why this is relevant, but just in case): 352.55 (non-free)

_I understand that you haven't specifically tested ahud for Linux, so if you can't help me here, that's fine._

On another note, I'm new to HUDs in general, so is there anyway to move or reduce the size of the damage numbers? It blocks the view of players' heads when I'm sniping if I bodyshoot on accident.

Thanks.

Image:
![snapshot0000](https://cloud.githubusercontent.com/assets/5037004/11971224/7bf32632-a8ee-11e5-9962-4e20d8b30edb.jpg)

**Comment by n0kk** [comment]
Interesting. I really can't say why it's rendering characters or letters in place of the scroll arrows or checkboxes. It's definitely using the HUD's font based on how they look, but I haven't touched anything related to checkboxes or scroll arrows in the longest time, and even then, it was only color changes. Font definitions haven't changed much either (you can find those in the `clientscheme.res` file). I've only been told the HUD works on Linux a few times, but seeing how sparse those reports have been, I can't tell at what point those things broke (or if it even breaks across different distros?? I dunno, I'm not very familiar with Linux). Unfortunately, I can't help you on my end. I'm hoping someone else can chime in here who uses this HUD on Linux.

As for the Notification alert, I recently changed that (along with the News and Contracts button) to use the Entypo symbols font instead of the default in-game images. Same font that the Home Server button uses. I see that the symbol fonts are a lot larger in your image than on Windows. They should be about the same size as the button images on the lower left. This may be why it appears shifted to the right. 

There's only one font definition for Entypo unfortunately (`SymbolS` in `clientscheme.res`with a tall value of 25) so you'll have to add another one if you want  to resize them. The buttons are in `resource\ui\mainmenuoverrride.res` and are `Notifications_ShowButtonPanel` (Alerts), `QuestLogButton` (Contracts), and `MOTD_ShowButtonPanel` (News). If that doesn't fix the issue where you click the original spot and its still shifted, I suspect it might be the way the symbols font is rendered on Linux? 

As for damage numbers, to resize them, open up `huddamageaccount.res` in `resource\ui` and change the font for `delta_item_font` and `delta_item_font_big`. There's no outlined fonts under 20 (except NormalCode12Outline, but I suspect that may be too small), so you'll have to try something like NormalCode18, NormalCode16, etc. (or add outlined font definitions to `clientscheme.res`). Increments of 2 should work fine up until you reach 8.

Sorry I couldn't be of more help!

**Comment by AgentTroll** [comment]
Ah, well thanks anyways. I guess its one of the problems with using linux :p

**Comment by n0kk** [comment]
Hmm, I'm not sure about the other elements and if they're tied to this, but the ammo disappearing is a known TF2 bug, not HUD. I'm not sure if they fixed it in any recent update since, but here's a fix someone posted that works: http://www.teamfortress.tv/27880/ammo-disappearing#13. Hope that helps.

**Comment by AgentTroll** [comment]
Thanks :)

**Comment by tadzik** [comment]
I have the same problem with ahud on Linux, the obfuscated checkboxes. Is it possible that you're using some font that's either not available on linuxes or uses some fancy characters in place of checkboxes? Is there something we can change locally to help you debug this?

**Comment by AgentTroll** [comment]
The new update looks awesome, although there is nothing about the characters has changed unfortunately. Also, agreed with @tadzik, is there anything that we could do on our side that could help you potentially find the root of this problem?

**Comment by n0kk** [comment]
You could attempt to change the font to another to see if the characters still show up, but other than that I really don't know unfortunately.

**Comment by katiepea** [comment]
the problem with this lies somewhere in the sourcescheme.res file, I don't know enough about how to troubleshoot exactly what it is, but I replaced sourcescheme.res from ahud with the one from rayshud and this issue disappeared. I then tried to determine what section of the file is causing issue, so I replaced just the font section and that fixes the issue as well.

**Comment by n0kk** [comment]
If you or anyone else can, try this edited ahud sourcescheme and let me know if the problem still exists:
[sourcescheme.zip](https://github.com/n0kk/ahud/files/157757/sourcescheme.zip)

**Comment by katiepea** [comment]
Nope, that still puts incorrect characters for display.

**Comment by n0kk** [comment]
Only differences from mine and the default sourcescheme (besides the small net graph and additional font definitions) are `MenuLarge` and `ServerBrowserTitle` (and more language ranges at the end for the TF2 Build font, but I don't think that should affect it). See if reverting `MenuLarge and/or `ServerBrowserTitle back to default does anything (default sourcescheme (here)[https://github.com/n0kk/tf2basehud/blob/master/resource/sourcescheme.res])
