### ISSUE TITLE
Classes of dead teammates hard to see

### ISSUE THREAD

**Issue by joelamos** [n0kk/ahud#69]
This is something that has been bothering me for awhile. Unless there is something very bright in the background behind the scoreboard, it is very hard to quickly identify the classes of dead teammates.
![hidden classes](https://cloud.githubusercontent.com/assets/5117047/15227845/178097ec-1857-11e6-81c9-476314494125.png)
Also, 69 lol

**Comment by n0kk** [comment]
Valve added a background to the playerlist that (as I know of) isn't possible to override, so that playerlist background combined with the normal scoreboard background have made it darker than usual. 

You can change the opacity of the scoreboard background to try to remedy this. To do this, open up `scoreboard.res` in `resource\ui`, find `ScoreboardBackground` and change the `fgcolor` value. (Default is `Hudblack` which equals 0 0 0 200 in RGBA, so try something less than 200).

**Comment by joelamos** [comment]
Thanks for the response. And is it possible to change the class icons?

**Comment by n0kk** [comment]
There's nothing in `scoreboard.res` to change those class icons other than its width. Whether you can change them via custom VTF files, I'm unsure, but I'd suspect not. Otherwise we would've seen custom icons by now from other HUD creators.

**Comment by joelamos** [comment]
Okay, thanks for the info. I'm closing this.
